# Generated by Django 4.2.7 on 2023-12-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stripe_shop", "0002_remove_order_product_order_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="tax",
        ),
        migrations.AlterField(
            model_name="item",
            name="currency",
            field=models.CharField(
                choices=[("RUB", "RUB"), ("USD", "USD")],
                max_length=3,
                verbose_name="валюта",
            ),
        ),
        migrations.DeleteModel(
            name="Discount",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Tax",
        ),
    ]
