# Generated by Django 4.2.7 on 2023-12-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stripe_shop", "0003_remove_order_discount_remove_order_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="currency",
            field=models.CharField(
                choices=[("USD", "USD"), ("RUB", "RUB")],
                max_length=3,
                verbose_name="валюта",
            ),
        ),
    ]
