# Generated by Django 4.2.7 on 2023-12-02 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stripe_shop", "0003_remove_order_discount_remove_order_product_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percent", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "скидка",
                "verbose_name_plural": "скидки",
            },
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tax_name",
                    models.TextField(
                        blank=True, null=True, verbose_name="наименование налога"
                    ),
                ),
                ("tax_percent", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "налог",
                "verbose_name_plural": "налоги",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="количество"),
                ),
                (
                    "stripe_id",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="id платежа на stripe",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(default=False, verbose_name="статус платежа"),
                ),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "discount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="cart.discount",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stripe_shop.item",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax",
                        to="cart.tax",
                    ),
                ),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "заказы",
            },
        ),
    ]
